#!/usr/bin/env python3
"""Download the Inter + JetBrains Mono latin woff2 subsets into public/assets/fonts
and regenerate public/assets/fonts.css.

Why: no third-party font CDN in production - one less DNS/TLS hop, no CSP holes,
no privacy leak to Google. Re-run any time to refresh the subsets.

    python3 ops/fetch_fonts.py
"""
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "public", "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "public", "assets", "fonts.css")
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
API = (
    "https://fonts.googleapis.com/css2?"
    "family=Inter:wght@400..900&family=JetBrains+Mono:wght@400..700&display=swap"
)
SUBSETS = ("latin", "latin-ext")


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> None:
    os.makedirs(FONT_DIR, exist_ok=True)
    css = get(API).decode()
    # blocks look like: /* latin */\n@font-face { ... }
    pairs = re.findall(r"/\*\s*([a-z\-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)
    out = [
        "/* ParkZone self-hosted fonts - generated by ops/fetch_fonts.py. Do not edit. */"
    ]
    saved = 0
    for subset, body in pairs:
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", body).group(1).strip()
        style = re.search(r"font-style:\s*([^;]+);", body).group(1).strip()
        url = re.search(r"url\((https://[^)]+)\)", body).group(1)
        rng = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()
        slug = family.lower().replace(" ", "-")
        name = f"{slug}-{subset}.woff2"
        dest = os.path.join(FONT_DIR, name)
        if not os.path.exists(dest):
            data = get(url)
            with open(dest, "wb") as fh:
                fh.write(data)
            print(f"downloaded {name} ({len(data)} bytes)")
        else:
            print(f"kept existing {name}")
        saved += 1
        out.append(
            "@font-face{font-family:'%s';font-style:%s;font-weight:%s;font-display:swap;"
            "src:url('./fonts/%s') format('woff2');unicode-range:%s}" % (family, style, weight, name, rng)
        )
    with open(CSS_OUT, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {CSS_OUT} with {saved} @font-face rules")


if __name__ == "__main__":
    main()
